{
 "title": "Linux node / fleet overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(node_uname_info{job=~\"integrations/(node_exporter|unix)\"}, cluster)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\", cluster=~\"$cluster\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{job=~\"integrations/(node_exporter|unix)|$datasource|$job\", cluster=~\"$cluster\", job=~\"$job\"},instance)"
    }
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "remnawave_users_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "remnawave_users_status{status=\"ACTIVE\"}",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "Users Online",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(remnawave_node_online_users)",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "Прирост пользователей",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "delta(remnawave_users_total[30d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MAU",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "count(count_over_time(remnawave_users_status{status=\"ACTIVE\"}[30d:1d]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections by Node",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "remnawave_node_online_users",
     "legendFormat": "{{node_country_emoji}} {{node_name}}"
    }
   ]
  },
  {
   "title": "Users Online",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(remnawave_node_online_users)",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Per-interface network traffic (receive and transmit) in bits per second",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{\r\n  cluster=~\"$cluster\",\r\n  job=~\"$job\",\r\n  instance=~\"$instance\",\r\n  device=~\"ens3|eth0|enp3s0|ens4\"\r\n}[$__rate_interval]) * 8",
     "legendFormat": "{{instance}} - Rx ens3"
    }
   ]
  },
  {
   "title": "Nodes status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "remnawave_node_status",
     "legendFormat": "{{node_country_emoji}} {{node_name}}"
    }
   ]
  },
  {
   "title": "Fleet overview",
   "type": "table",
   "description": "All nodes' perfomance at a glance.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "node_uname_info{cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"} \n* on (cluster,job,instance)\ngroup_left(pretty_name)\nnode_os_info{cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}\n"
    },
    {
     "expr": "time() - node_boot_time_seconds{cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}"
    },
    {
     "expr": "node_load1{cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "count without (cpu) (node_cpu_seconds_total{cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\", mode=\"idle\"})",
     "legendFormat": "Cores"
    },
    {
     "expr": "(((count by (instance) (count(node_cpu_seconds_total{cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}) by (cpu, instance))) \n- \navg by (instance) (sum by (instance, mode)(irate(node_cpu_seconds_total{mode='idle',cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))) * 100) \n/ \ncount by(instance) (count(node_cpu_seconds_total{cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}) by (cpu, instance))\n",
     "legendFormat": "CPU usage"
    },
    {
     "expr": "node_memory_MemTotal_bytes{cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Memory total"
    },
    {
     "expr": "100 -\n(\n  avg by (instance) (node_memory_MemAvailable_bytes{cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}) /\n  avg by (instance) (node_memory_MemTotal_bytes{cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"})\n* 100\n)\n"
    },
    {
     "expr": "node_filesystem_size_bytes{cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\", mountpoint=\"/\", fstype!=\"rootfs\"}"
    },
    {
     "expr": "100 - node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\", cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}/node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\", cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}*100"
    },
    {
     "expr": "count by (instance) (max_over_time(ALERTS{cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\", alertstate=\"firing\", severity=\"critical\"}[1m])) * group by (instance) (node_uname_info{cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"})"
    },
    {
     "expr": "count by (instance) (max_over_time(ALERTS{cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\", alertstate=\"firing\", severity=\"warning\"}[1m])) * group by (instance) (node_uname_info{cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Users online history",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "remnawave_node_online_users",
     "legendFormat": "{{node_country_emoji}} {{node_name}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Top 25",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(25,\n  100 - avg by (job, instance) (\n    rate(node_cpu_seconds_total{\n      cluster=~\"$cluster\",\n      job=~\"$job\",\n      instance=~\"$instance\",\n      mode=\"idle\"\n    }[$__rate_interval])\n  ) * 100\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Top 25",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(25, 100 -\n(\n  avg by (job, instance) (\n    node_memory_MemAvailable_bytes{cluster=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}\n  )\n  /\n  avg by (job, instance) (\n    node_memory_MemTotal_bytes{cluster=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}\n  )\n) * 100)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}